// Code generated by "stringer -type=MorseMode"; DO NOT EDIT.

package morse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TextFile-0]
	_ = x[CodeGroup-1]
	_ = x[CodeAlnum-2]
	_ = x[CodeNum-3]
	_ = x[TopWords-4]
	_ = x[Qcode-5]
	_ = x[MorseChar-6]
	_ = x[Koch-7]
}

const _MorseMode_name = "TextFileCodeGroupCodeAlnumCodeNumTopWordsQcodeMorseCharKoch"

var _MorseMode_index = [...]uint8{0, 8, 17, 26, 33, 41, 46, 55, 59}

func (i MorseMode) String() string {
	if i >= MorseMode(len(_MorseMode_index)-1) {
		return "MorseMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MorseMode_name[_MorseMode_index[i]:_MorseMode_index[i+1]]
}
